/// Golden Rules enforcement tests — generated by spine-rules.
use spine_rules::golden_rules_suite;

golden_rules_suite! {
    binary: env!("CARGO_BIN_EXE_vacuum"),
    operator_json: include_str!("../operator.json"),
    source_files: &["src/refusal/codes.rs", "src/walk/walker.rs"],
    exit_code_1_required: false,
}
